//layout.tsx

import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


import { Comfortaa, Kanit } from "next/font/google";

const comfortaa = Comfortaa({
  subsets: ["latin"],
  variable: "--font-comfortaa",
  weight: ["400", "500", "700"],
  style: ['normal'], // หรือเพิ่มได้ตามที่ใช้
});

const kanit = Kanit({
  subsets: ["thai", "latin"],
  variable: "--font-kanit",
  weight: ["400", "500", "700"],
  style: ['normal', 'italic'],
});


export const metadata: Metadata = {
  title: "Khong Van Transport",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.variable} ${comfortaa.variable}  font-sans`}>
        {children}
      </body>
    </html>
  );
}
