import type { Metadata } from "next";
import "./globals.css";
import { Comfortaa, Kanit } from "next/font/google";

const comfortaa = Comfortaa({
  subsets: ["latin"],
  variable: "--font-comfortaa",
  weight: ["400", "500", "700"],
  style: ["normal"],
});

const kanit = Kanit({
  subsets: ["thai", "latin"],
  variable: "--font-kanit",
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Khong Van Transport",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      {/* สำคัญ: อย่าใส่ class bg-* บน body เพื่อไม่ให้ทับ gradient จาก globals.css */}
      <body className={`${kanit.variable} ${comfortaa.variable} font-sans antialiased min-h-screen`}>
        {children}
      </body>
    </html>
  );
}
